### ISSUE TITLE
[TS] error in simple method delegating a message

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#1168]
Another issue while still trying to find the root cause of the error on my example..
This one seems pretty basic

```wollok
object booleanConditionError {
	method m() {
		return rules.a()
	}
}
object rules {
	method a() = true
}
```

This raises the `EValidator` error.
Commenting the `m()` method declaration makes it work.
Also rules.a() gets typed to Any when the TS fails.
Is like a failure typing m() makes the whole program to get untyped.

This other syntax also makes it fail

```wollok
object booleanConditionError {
	method m() = rules.a()
}
```

**Comment by javierfernandes** [comment]
Seems like pretty blocker

**Comment by javierfernandes** [comment]
@npasserini showstopper ?

**Comment by npasserini** [comment]
Easy.

2017-07-28 11:08 GMT-03:00 Javier Fernandes <notifications@github.com>:

**Comment by npasserini** [comment]
Fixed in https://github.com/uqbar-project/wollok/pull/1170

**Comment by javierfernandes** [comment]
This still fails in 1.6.1

```
class Color {
	const nombre
	constructor(n) { nombre = n }
	method esEstrambotico() { return nombre == "Violeta" }
}
```

Is not delegating but just comparing a field with a string.
I can create a new issue if it is a different case

**Comment by npasserini** [comment]
Good report, it would be great to create a new issue.

2017-08-01 9:27 GMT-03:00 Javier Fernandes <notifications@github.com>:

**Comment by javierfernandes** [comment]
I did. Just forget to add here this #1187
